### ISSUE TITLE
Need the support libraries to compile - hri, etc

### ISSUE THREAD

**Issue by ramiss** [jeremyherbert/playful-turtle-xiao#1]
Hi There,

Thanks for this and I'd love to try it on my new XIAO.  Unfortunately your code won't compile without the libraries.  For example, the hri_sercomspi_ functions are all undefined without  hri/hri_nvmctrl_d21.h 

Could you zip those up and include them?  Technically we need all of the following:

#include "hal/include/hal_gpio.h"
#include "hal/include/hal_init.h"
#include "hri/hri_nvmctrl_d21.h"
#include "hpl/gclk/hpl_gclk_base.h"
#include "hpl_pm_config.h"
#include "hpl/pm/hpl_pm_base.h"
#include "tusb.h"
#include "SEGGER_RTT.h"
#include "ringbuf.h"

Thanks!

Richard

**Comment by jeremyherbert** [comment]
These libraries are included via the tinyusb git submodule, so you’ll need to update them recursively. See https://stackoverflow.com/questions/10168449/git-update-submodules-recursively for more details.

Also, if you just want to play with it there is a prebuilt binary in the releases section that you can just drag+drop.

**Comment by ramiss** [comment]
Thank you.  My project is to try and put the XIAO into slave mode and i've had a heck of a time as the generic Sercom0 code doesn't "seem" to work, so I was hoping to try yours.  I'll have a look for the tinyusb git submodule code.

**Comment by jeremyherbert** [comment]
To be honest with you, this was my first project with an Atmel ARM device, and I just wrote the SERCOM code on a register level by reading the datasheet and ignoring most of the atmel START code. The hri functions are just bit twiddling register bits. I found the datasheet descriptions much clearer than the HAL code.

**Comment by ramiss** [comment]
Just wanted to say thanks again for the help.  I managed to boil down only the absolutely necessary functions to turn the XIAO into a slave, and gave you thanks for the assist:
[https://github.com/ramiss/SeeeduinoXIAO_SPISlave](https://github.com/ramiss/SeeeduinoXIAO_SPISlave)

**Comment by jeremyherbert** [comment]
Great! Glad you were able to get it working.
